name: build

on:
  push:
  pull_request:

jobs:
  build-macos-platforms:
    runs-on: macos-10.15
    strategy:
        matrix:
            cfg:
            - {target: osx, job: 1, cc: "clang", cxx: "clang++"}
            - {target: osx, job: 2, cc: "clang", cxx: "clang++"}
            - {target: osx, job: 3, cc: "clang", cxx: "clang++"}
            - {target: osx, job: 4, cc: "clang", cxx: "clang++"}
    env:
       TARGET: ${{matrix.cfg.target}}
       BUNDLE: ${{matrix.cfg.job}}
    steps:
      - uses: actions/checkout@v2
      - name: Scripts Calc Formula - ${{matrix.cfg.target}} Bundle ${{matrix.cfg.job}}
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh
        env:
            DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
            # SDKROOT: "Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"


