name: build

on:
  push:
  pull_request:

jobs:
  build-ios:
    runs-on: macos-10.15
    env:
        TARGET: ios
    strategy:
        matrix:
            job: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
        env:
            BUNDLE: $JOB
      - name: Scripts Calc Formula
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh
