name: build

on:
  push:
  pull_request:

jobs:
  build-macos-platforms:
    runs-on: macos-10.15
    strategy:
        matrix:
            cfg:
            - {target: osx, job: 1}
            - {target: osx, job: 2}
            - {target: osx, job: 3}
            - {target: osx, job: 4}
    env:
       TARGET: ${{matrix.cfg.target}}
       BUNDLE: ${{matrix.cfg.job}}
       DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
       SDKROOT: "/Applications/Xcode_12.2.app/Contents/Developer"
    steps:
      - uses: actions/checkout@v2
      - name: Scripts Calc Formula - ${{matrix.cfg.target}} Bundle ${{matrix.cfg.job}}
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh
        env:
            DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
            SDKROOT: "$DEVELOPER_DIR/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk"


