name: build

on:
  push:
  pull_request:

jobs:
  build-ios:
    runs-on: macos-10.15
    env:
        TARGET: ios
    strategy:
        matrix:
            job: [1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.5
        with:
          cmake-version: '3.16.x'
      - name: Scripts Calc Formula - Bundle ${{matrix.job}}
        run: ./scripts/calculate_formulas.sh
        env:
            BUNDLE: ${{matrix.job}}
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh
        env:
            BUNDLE: ${{matrix.job}}
