name: build

on:
  push:
  pull_request:

jobs:
  build-macos-platforms:
    runs-on: macos-10.15
    strategy:
        matrix:
            cfg:
            - {target: osx, job: 1}
            - {target: osx, job: 2}
            - {target: osx, job: 3}
            - {target: osx, job: 4}
            - {target: ios, job: 1}
            - {target: ios, job: 2}
            - {target: ios, job: 3}
            - {target: ios, job: 4}
            - {target: tvos, job: 1}
            - {target: tvos, job: 2}
            - {target: tvos, job: 3}
            - {target: tvos, job: 4}
    steps:
      - uses: actions/checkout@v2
      - name: Scripts Calc Formula - ${{matrix.cfg.target}} Bundle ${{matrix.cfg.job}}
        run: ./scripts/calculate_formulas.sh
        env:
            BUNDLE: ${{matrix.cfg.job}}
      - name: Scripts Install
        run: ./scripts/${{matrix.cfg.target}}/install.sh
      - name: Build
        run: ./scripts/build.sh
        env:
            BUNDLE: ${{matrix.cfg.job}}
