name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15
    env:
        TARGET: ios
        BUNDLE: 2
        ROOT_DIR: ../../
    steps:
      - name: Scripts Calc Formula
        run: ./${ROOT_DIR}scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./${ROOT_DIR}scripts/$TARGET/install.sh
      - name: Build
        run: ./${ROOT_DIR}scripts/build.sh

