name: build

on:
  push:
  pull_request:

jobs:
  build-macos-platforms:
    runs-on: macos-10.15
    strategy:
        matrix:
            cfg:
            - {target: osx, job: 2}
    env:
       TARGET: ${{matrix.cfg.target}}
       BUNDLE: ${{matrix.cfg.job}}
       DEVELOPER_DIR: "/Applications/Xcode_12.2.app/Contents/Developer"
    steps:
      - uses: actions/checkout@v2
      - name: Scripts Calc Formula - $TARGET Bundle $BUNDLE
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh
