name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-10.15
    env:
        TARGET: ios
        BUNDLE: 2
        DEVELOPER_DIR: /Applications/Xcode-12.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Scripts Calc Formula
        run: ./scripts/calculate_formulas.sh
      - name: Scripts Install
        run: ./scripts/$TARGET/install.sh
      - name: Build
        run: ./scripts/build.sh

